# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/directory_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogDirectoryUpdate(object):
    def setupUi(self, DialogDirectoryUpdate):
        DialogDirectoryUpdate.setObjectName("DialogDirectoryUpdate")
        DialogDirectoryUpdate.resize(827, 415)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogDirectoryUpdate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelID = QtWidgets.QLabel(DialogDirectoryUpdate)
        self.labelID.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.labelID.setObjectName("labelID")
        self.gridLayout.addWidget(self.labelID, 0, 0, 1, 1)
        self.lineEditID = QtWidgets.QLineEdit(DialogDirectoryUpdate)
        self.lineEditID.setReadOnly(True)
        self.lineEditID.setObjectName("lineEditID")
        self.gridLayout.addWidget(self.lineEditID, 0, 1, 1, 1)
        self.labelName = QtWidgets.QLabel(DialogDirectoryUpdate)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 1, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(DialogDirectoryUpdate)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tableViewDirectoryValues = QtWidgets.QTableView(DialogDirectoryUpdate)
        self.tableViewDirectoryValues.setObjectName("tableViewDirectoryValues")
        self.tableViewDirectoryValues.horizontalHeader().setStretchLastSection(True)
        self.tableViewDirectoryValues.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableViewDirectoryValues)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonNew = QtWidgets.QPushButton(DialogDirectoryUpdate)
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.horizontalLayout.addWidget(self.pushButtonNew)
        self.pushButtonDelete = QtWidgets.QPushButton(DialogDirectoryUpdate)
        self.pushButtonDelete.setEnabled(False)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout.addWidget(self.pushButtonDelete)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogDirectoryUpdate)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogDirectoryUpdate)
        self.buttonBox.accepted.connect(DialogDirectoryUpdate.accept)  # type: ignore
        self.buttonBox.rejected.connect(DialogDirectoryUpdate.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogDirectoryUpdate)

    def retranslateUi(self, DialogDirectoryUpdate):
        _translate = QtCore.QCoreApplication.translate
        DialogDirectoryUpdate.setWindowTitle(
            _translate("DialogDirectoryUpdate", "Directory update")
        )
        self.labelID.setText(_translate("DialogDirectoryUpdate", "Directory ID:"))
        self.labelName.setText(_translate("DialogDirectoryUpdate", "Название:"))
        self.pushButtonNew.setText(_translate("DialogDirectoryUpdate", "NEW"))
        self.pushButtonDelete.setText(_translate("DialogDirectoryUpdate", "DELETE"))
