# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/directories.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogDirectories(object):
    def setupUi(self, DialogDirectories):
        DialogDirectories.setObjectName("DialogDirectories")
        DialogDirectories.resize(805, 468)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogDirectories)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableViewDirectories = QtWidgets.QTableView(DialogDirectories)
        self.tableViewDirectories.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers
        )
        self.tableViewDirectories.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection
        )
        self.tableViewDirectories.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows
        )
        self.tableViewDirectories.setObjectName("tableViewDirectories")
        self.tableViewDirectories.horizontalHeader().setStretchLastSection(True)
        self.tableViewDirectories.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableViewDirectories)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonNew = QtWidgets.QPushButton(DialogDirectories)
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.horizontalLayout.addWidget(self.pushButtonNew)
        self.pushButtonDelete = QtWidgets.QPushButton(DialogDirectories)
        self.pushButtonDelete.setEnabled(False)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout.addWidget(self.pushButtonDelete)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogDirectories)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogDirectories)
        self.buttonBox.accepted.connect(DialogDirectories.accept)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogDirectories)

    def retranslateUi(self, DialogDirectories):
        _translate = QtCore.QCoreApplication.translate
        DialogDirectories.setWindowTitle(_translate("DialogDirectories", "Directories"))
        self.pushButtonNew.setText(_translate("DialogDirectories", "NEW"))
        self.pushButtonDelete.setText(_translate("DialogDirectories", "DELETE"))
