# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/new_directory.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogNewDirectory(object):
    def setupUi(self, DialogNewDirectory):
        DialogNewDirectory.setObjectName("DialogNewDirectory")
        DialogNewDirectory.resize(360, 100)
        DialogNewDirectory.setMinimumSize(QtCore.QSize(360, 100))
        self.gridLayout = QtWidgets.QGridLayout(DialogNewDirectory)
        self.gridLayout.setObjectName("gridLayout")
        self.labelName = QtWidgets.QLabel(DialogNewDirectory)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 0, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(DialogNewDirectory)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogNewDirectory)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 2)

        self.retranslateUi(DialogNewDirectory)
        self.buttonBox.accepted.connect(DialogNewDirectory.accept)  # type: ignore
        self.buttonBox.rejected.connect(DialogNewDirectory.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogNewDirectory)

    def retranslateUi(self, DialogNewDirectory):
        _translate = QtCore.QCoreApplication.translate
        DialogNewDirectory.setWindowTitle(_translate("DialogNewDirectory", "Dialog"))
        self.labelName.setText(_translate("DialogNewDirectory", "Название:"))
