# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/new_directory_value.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogNewDirectoryValue(object):
    def setupUi(self, DialogNewDirectoryValue):
        DialogNewDirectoryValue.setObjectName("DialogNewDirectoryValue")
        DialogNewDirectoryValue.resize(360, 120)
        DialogNewDirectoryValue.setMinimumSize(QtCore.QSize(360, 120))
        self.gridLayout = QtWidgets.QGridLayout(DialogNewDirectoryValue)
        self.gridLayout.setObjectName("gridLayout")
        self.labelKey = QtWidgets.QLabel(DialogNewDirectoryValue)
        self.labelKey.setObjectName("labelKey")
        self.gridLayout.addWidget(self.labelKey, 0, 0, 1, 1)
        self.lineEditKey = QtWidgets.QLineEdit(DialogNewDirectoryValue)
        self.lineEditKey.setObjectName("lineEditKey")
        self.gridLayout.addWidget(self.lineEditKey, 0, 1, 1, 1)
        self.labelValue = QtWidgets.QLabel(DialogNewDirectoryValue)
        self.labelValue.setObjectName("labelValue")
        self.gridLayout.addWidget(self.labelValue, 1, 0, 1, 1)
        self.lineEditValue = QtWidgets.QLineEdit(DialogNewDirectoryValue)
        self.lineEditValue.setObjectName("lineEditValue")
        self.gridLayout.addWidget(self.lineEditValue, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogNewDirectoryValue)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)

        self.retranslateUi(DialogNewDirectoryValue)
        self.buttonBox.accepted.connect(DialogNewDirectoryValue.accept)  # type: ignore
        self.buttonBox.rejected.connect(DialogNewDirectoryValue.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogNewDirectoryValue)

    def retranslateUi(self, DialogNewDirectoryValue):
        _translate = QtCore.QCoreApplication.translate
        DialogNewDirectoryValue.setWindowTitle(
            _translate("DialogNewDirectoryValue", "New directory value")
        )
        self.labelKey.setText(_translate("DialogNewDirectoryValue", "Ключ:"))
        self.labelValue.setText(_translate("DialogNewDirectoryValue", "Значение:"))
