# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/template_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetTemplateItem(object):
    def setupUi(self, WidgetTemplateItem):
        WidgetTemplateItem.setObjectName("WidgetTemplateItem")
        WidgetTemplateItem.resize(600, 150)
        WidgetTemplateItem.setMinimumSize(QtCore.QSize(600, 150))
        self.gridLayout = QtWidgets.QGridLayout(WidgetTemplateItem)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelName = QtWidgets.QLabel(WidgetTemplateItem)
        self.labelName.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.labelName.setObjectName("labelName")
        self.verticalLayout_4.addWidget(self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(WidgetTemplateItem)
        self.lineEditName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditName.setReadOnly(True)
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout_4.addWidget(self.lineEditName)
        self.labelDescription = QtWidgets.QLabel(WidgetTemplateItem)
        self.labelDescription.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.labelDescription.setObjectName("labelDescription")
        self.verticalLayout_4.addWidget(self.labelDescription)
        self.lineEditDescription = QtWidgets.QLineEdit(WidgetTemplateItem)
        self.lineEditDescription.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditDescription.setObjectName("lineEditDescription")
        self.verticalLayout_4.addWidget(self.lineEditDescription)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 2, 1)
        self.tabWidget = QtWidgets.QTabWidget(WidgetTemplateItem)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPattern = QtWidgets.QWidget()
        self.tabPattern.setObjectName("tabPattern")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabPattern)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditPattern = QtWidgets.QLineEdit(self.tabPattern)
        self.lineEditPattern.setObjectName("lineEditPattern")
        self.verticalLayout_2.addWidget(self.lineEditPattern)
        self.tabWidget.addTab(self.tabPattern, "")
        self.tabDirectories = QtWidgets.QWidget()
        self.tabDirectories.setObjectName("tabDirectories")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabDirectories)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBoxDirectories = QtWidgets.QComboBox(self.tabDirectories)
        self.comboBoxDirectories.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBoxDirectories.setSizeAdjustPolicy(
            QtWidgets.QComboBox.AdjustToContents
        )
        self.comboBoxDirectories.setObjectName("comboBoxDirectories")
        self.comboBoxDirectories.addItem("")
        self.comboBoxDirectories.setItemText(0, "")
        self.verticalLayout.addWidget(self.comboBoxDirectories)
        self.tabWidget.addTab(self.tabDirectories, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelDefaultDirectories = QtWidgets.QLabel(WidgetTemplateItem)
        self.labelDefaultDirectories.setObjectName("labelDefaultDirectories")
        self.verticalLayout_3.addWidget(self.labelDefaultDirectories)
        self.lineEditDefault = QtWidgets.QLineEdit(WidgetTemplateItem)
        self.lineEditDefault.setPlaceholderText("")
        self.lineEditDefault.setObjectName("lineEditDefault")
        self.verticalLayout_3.addWidget(self.lineEditDefault)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)

        self.retranslateUi(WidgetTemplateItem)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(WidgetTemplateItem)

    def retranslateUi(self, WidgetTemplateItem):
        _translate = QtCore.QCoreApplication.translate
        WidgetTemplateItem.setWindowTitle(
            _translate("WidgetTemplateItem", "template_item")
        )
        self.labelName.setText(_translate("WidgetTemplateItem", "Название:"))
        self.labelDescription.setText(_translate("WidgetTemplateItem", "Описание:"))
        self.lineEditPattern.setPlaceholderText(
            _translate("WidgetTemplateItem", "Значение: {value}")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tabPattern),
            _translate("WidgetTemplateItem", "F cтрока"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tabDirectories),
            _translate("WidgetTemplateItem", "Значение каталога"),
        )
        self.labelDefaultDirectories.setText(
            _translate("WidgetTemplateItem", "Значение по умолчанию:")
        )
